const data = {
  products: [
    {
      name: "Night light",
      id: 1,
      category: "night lights",
      image: ".../public/image/p1.jpg",
      price: 30,
      countStock: 12,
      rating: 4.5,
      numReviews: 10,
      description: "Salt lamps from himalayan salt",
    },
    {
      name: "Night light",
      id: 2,
      category: "night lights",
      image: "/images/p1.jpg",
      price: 30,
      countStock: 12,
      rating: 4.5,
      numReviews: 10,
      description: "Salt lamps from himalayan salt",
    },
    {
      name: "Night light",
      id: 3,
      category: "night lights",
      image: "/images/p1.jpg",
      price: 30,
      countStock: 12,
      rating: 4.5,
      numReviews: 10,
      description: "Salt lamps from himalayan salt",
    },
    {
      name: "Night light",
      id: 4,
      category: "night lights",
      image: "/images/p1.jpg",
      price: 30,
      countStock: 12,
      rating: 4.5,
      numReviews: 10,
      description: "Salt lamps from himalayan salt",
    },
  ],
};
export default data;
